### PR TITLE
[DO NOT MERGE] Enable PropertyAccess's cache

### PR DESCRIPTION
**Pull request by dunglas**
To test if it changes something. (I try to understand why results are so different on my box and in the Travis's container.)

### CODE REVIEW

**Comment by dunglas** [comment]
I think I got it :) APCu isn't enabled on Travis.

**Comment by egeloen** [comment]
Indeed, I miss it... Can you enable it?

**Comment by egeloen** [comment]
I just fixed it

**Comment by egeloen** [comment]
Can you rebase?

**Comment by egeloen** [comment]
I added more caching in b2c833783c5cb2d384fb4ef671fc1d75933aed51

**Comment by egeloen** [comment]
Let close it, everything is already in master :)

**Pull request closed without merging**
