### PR TITLE
Optimize Travis config. Test with HHVM.

### PR DESCRIPTION
**Pull request by dunglas**
The Travis config has been imported from Symfony and include some more optimizations for performance and fair benchmarking (like disabling the GC).

### CODE REVIEW

**Comment by egeloen** [comment]
Disabling GC this way: https://github.com/egeloen/ivory-serializer-benchmark/blob/master/bin/benchmark#L8 is not a good way?

**Comment by dunglas** [comment]
@egeloen didn't looked at this file :) Looks good too!

Btw, using the APC class loader isn't necessary anymore: https://github.com/symfony/symfony-standard/pull/964

**Comment by egeloen** [comment]
Nice, let remove it then :) An other question: does it make sense to rely on APC/APCu for PSR-6 cache or does the filesystem can be used?

**Comment by dunglas** [comment]
APCu is faster (IIRC).

**Comment by egeloen** [comment]
@dunglas Have you been able to spot the bottleneck in the Symfony benchmark?

**Comment by dunglas** [comment]
Not yet I'll be very busy this week. I didn't understand why results are so different on my local computer than on Travis. My be should we warm the APCu cache before running the benchmark (run it twice to emulate the second HTTP request).
When I'll have some free time I'll take the time to profile the benchmark using Blackfire.

Can you share the results you have on your local computer to compare?

Do you have the same results

**Pull request closed without merging**
