### PR TITLE
Use Symfony 4, test with PHP 7.2

### PR DESCRIPTION
**Pull request by dunglas**

### CODE REVIEW

**Comment by goetas** [comment]
yay, green!

**Comment by goetas** [comment]
@egeloen any chance to see this merged?

**Comment by goetas** [comment]
I have forked this repo in https://github.com/php-serializers/ivory-serializer-benchmark and created a `php-serializers` github org.

I have merged this PR in the fork.

I invite you to use https://github.com/php-serializers/ivory-serializer-benchmark for benchmarking PHP serializer libraries

**Comment by dunglas** [comment]
Thanks @goetas!

**Pull request closed without merging**
